README.md, lib/message_queue_consumer/support/shared_examples_for_message_processor.rb
After https://github.com/alphagov/message-queue-consumer/pull/1 was merged, an attempt at using the gem found some improvements would be helpful.
This PR adds shared examples to simplify testing the client specific message processor, and updates examples and wording in the README.
Part of ticket: https://trello.com/c/z8b6VmCU/317-update-panopticon-when-links-are-sent-to-publishing-api
=> Add rspec shared examples and update README

CHANGELOG.md, lib/message_queue_consumer/version.rb
Need to set an initial version of the gem. There will probably be other tweaks to it, so decided not to choose 1.0.0…
Also add a changelog for future changes.
Part of ticket: https://trello.com/c/z8b6VmCU/317-update-panopticon-when-links-are-sent-to-publishing-api
=> Set the version number for the gem

govuk-message-queue-consumer.gemspec, jenkins_branches.sh
From rubygems.org:
> USE UNDERSCORES FOR MULTIPLE WORDS
> If a class or module has multiple words, use underscores to separate
them. This matches the file the user will require, making it easier for
the user to start using your gem.
http://guides.rubygems.org/name-your-gem/
The convention is to use underscores for classes (`ruby_parser` -> `RubyParser`) and dashes for namespaces (`rdoc-data` -> `RDoc::Data`). This is also in our styleguide[1].
This correction didn't happen in the previous PR (#7) because I was under the impression that the convention was being broken consistently in our gems. After auditing half the gems owned by GOV.UK[1] it seems about 75% are correctly named, so we should keep this up.
[1] https://github.com/alphagov/styleguides/blob/master/rubygems.md#naming
[2] …
=> Rename gem to use use correct convention

README.md, lib/govuk_message_queue_consumer/test_helpers.rb, lib/govuk_message_queue_consumer/test_helpers/shared_examples.rb
This PR makes the test helpers easier to use by adding a complete example in the README. It also corrects the terminology to use "processor" consistently and makes the `require` less verbose.
=> Make test helpers easier to use

CHANGELOG.md, lib/govuk_message_queue_consumer/version.rb
The first PR that uses this gem (https://github.com/alphagov/content-register/pull/28) is almost finished. Since that would mean this gem is used in production, semver dictates that we release 1.0.0.
=> Release 1.0.0

tasks/publish_gem.rake
This was forgotten in the rename. Correcting it will allow `gem_publisher` to publish the gem.
=> Fix gemspec location

lib/govuk_message_queue_consumer/consumer.rb
This comment was taken from the email-alert-service and explains why we prefetch only one message: https://github.com/alphagov/email-alert-service/commit/30eb96fbd36363e7c79d72d505e69db84f20e1b8
=> Document why why only prefetch one message

lib/govuk_message_queue_consumer/test_helpers/shared_examples.rb
Some projects don't use rspecm, but want to use the test helpers. To allow users to use `require 'govuk_message_queue_consumer/test_helpers'` regardless of test framework, we should wrap framework-specific code in a conditional.
=> Only add shared examples for RSpec projects

CHANGELOG.md, README.md, lib/govuk_message_queue_consumer/test_helpers.rb, lib/govuk_message_queue_consumer/test_helpers/mock_message.rb, spec/mock_message_spec.rb
`GovukMessageQueueConsumer::MockMessage` can be used to mock messages from RabbitMQ. Usage is documented in the README. When there are live examples, those will be added as a reference.
=> Add GovukMessageQueueConsumer::MockMessage

lib/govuk_message_queue_consumer/consumer.rb, spec/consumer_spec.rb
The `routing_key` is the pattern that is used to listen to specific messages. We publish messages to the content queue with `#{format}.#{update_type}`.
`email-alert-service` uses this to subscribe to major updates, because it only wants to send out emails when something significant changes.
=> Add option to specify a routing key

lib/govuk_message_queue_consumer.rb, lib/govuk_message_queue_consumer/consumer.rb, lib/govuk_message_queue_consumer/json_processor.rb, lib/govuk_message_queue_consumer/message.rb, lib/govuk_message_queue_consumer/test_helpers/mock_message.rb, spec/consumer_spec.rb, spec/json_processor_spec.rb, spec/message_spec.rb
`email-alert-service`, one of the apps that will use this gem, has special behaviour for when the message received from RMQ isn't valid JSON. This may be a good thing to pull up into the gem.
We implement the check by refactoring the JSON parsing into a middleware processor, like `HeartbeatProcessor`. The responsibility of the `JSONProcessor` is to parse the `payload` attribute on `Message`.
I've considered an alternative, to keep the JSON parsing inside `Message`, but that would've meant that `Message` would discard itself whenever it encounters a parse error. Keeping this within a class seemed cleaner.
`Message` has been refactored to have use `payload` consistently. This is also the term RabbitMQ uses.
=> Handle invalid JSON

README.md, lib/govuk_message_queue_consumer/consumer.rb, lib/govuk_message_queue_consumer/test_helpers.rb, lib/govuk_message_queue_consumer/test_helpers/test_consumer.rb, spec/consumer_spec.rb
This message can be used by the consumers in an integration test. We add this method here to avoid exposing `exchange` publicly.
The first commit refactors `Consumer` to make this change easier.
=> Add TestConsumer

lib/govuk_message_queue_consumer/message.rb, lib/govuk_message_queue_consumer/test_helpers/mock_message.rb
This makes it easier to implement new methods and ensure they have the same interface.
=> Make MockMessage inherit from Message

README.md, lib/govuk_message_queue_consumer/rabbitmq_config.rb, spec/rabbitmq_config_spec.rb, spec/spec_helper.rb
5672 is the well-known default port for RabbitMQ. It is very unlikely this will ever be different across environment or applications. Bunny uses the port as a default, so this has no effect.
Bunny defaults: https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L93
=> Use default port for RabbitMQ

lib/govuk_message_queue_consumer/test_helpers/mock_message.rb, lib/govuk_message_queue_consumer/test_helpers/test_consumer.rb, spec/json_processor_spec.rb, spec/mock_message_spec.rb
Old queues and routing keys hanging around after the tests finish can cause confusion.
Purge the queue of messages and unbind the queue from the exchange
This PR needs to be merged and then the gem version bumped, etc, before these dependent PRs can be merged:
https://github.com/alphagov/email-alert-service/pull/42
https://github.com/alphagov/content-register/pull/28
=> Improve testing

lib/govuk_message_queue_consumer/consumer.rb, lib/govuk_message_queue_consumer/message.rb, lib/govuk_message_queue_consumer/test_helpers/mock_message.rb, spec/consumer_spec.rb, spec/json_processor_spec.rb, spec/message_spec.rb
By reordering the parameters from most-used to least-used, we can
declutter the tests in consuming apps in the most common scenario:
```
MockMessage.new({}, {}, payload)
```
vs
```
MockMessage.new(payload)
```
This was originally done in https://github.com/alphagov/govuk_message_queue_consumer/pull/24.
=> Flip the parameters to `Message`

lib/govuk_message_queue_consumer/consumer.rb
Airbrake is enabled on most of our projects, so we should send errors there to notify developers.
Trello: https://trello.com/c/lRnxI2x5
=> Forward uncaught exception to Airbrake

.gitignore, CHANGELOG.md, README.md, govuk_message_queue_consumer.gemspec, lib/govuk_message_queue_consumer/consumer.rb, lib/govuk_message_queue_consumer/message.rb, lib/govuk_message_queue_consumer/null_statsd.rb, spec/consumer_spec.rb, spec/consumer_with_statsd_spec.rb, spec/message_spec.rb, spec/support/queue_helpers.rb
This PR adds statsd support to this gem. When passed in a client, the consumer will start incrementing counters for the number of processed, failed, retried and errored messages. 
This will allow us to build a dashboard and add alerting for specific queues.
Trello: https://trello.com/c/Ipl9UVsA
=> Add statsd support

govuk_message_queue_consumer.gemspec
There is no need to include test files in a gem that will be used in production
Whilst it is true that not all gems are production ready, here at GOV.UK we shouldn't be shipping to production gems that contain test files.
Test files are completely useless in a production environment, besides providing them in a production environment can be very dangerous as it would be very easy to make a mistake.
For example we could be mocking the real Object that is used in production by accident.
Consider that we have mocked Bunny and accidentally we have executed the following in production, our RabbitMQ will never receive the data we were expecting.
```ruby
queue = instance_double('Bunny::Queue', bind: nil, subscribe: '')
channel = instance_double('Bunny::Channel', queue: queue, prefetch: nil, …
```
=> Don't build test files in the gem

lib/govuk_message_queue_consumer/test_helpers.rb
This was removed on PR [#34](https://github.com/alphagov/govuk_message_queue_consumer/pull/34/files#diff-00df42adf44cc945c8526a5a28c3dca1L1)
I have double checked that this is not breaking tests on Rummager and Panopticon (which use this gem)
=> Remove test_consumer from test_helpers

spec/mock_message_spec.rb, spec/test_helpers/mock_message_spec.rb, spec/test_helpers/shared_examples_spec.rb
This improves the testing of the test helpers, so that https://github.com/alphagov/govuk_message_queue_consumer/pull/36 can't happen again.
=> Add more tests for test helpers

CHANGELOG.md, lib/govuk_message_queue_consumer/version.rb
This version solves the problem of requiring a previously deleted file,
we have taken action to prevent this from happening again by adding extra specs for our test_helper files.
=> Update gem version to 3.0.1

README.md
I would like to know which projects are using a certain gem just by reading the `README.md` file.
I also would like to propose this as a common practice along all gems we are responsible for.
=> Add information about projects using this gem

README.md
Both of these apps have been retired.
https://trello.com/c/dGPNmVub
=> Remove references to panopticon and content-register

CHANGELOG.md, lib/govuk_message_queue_consumer/version.rb
Since we switched to bundler 1.14, we've been unable to build rummager,
which depends on this gem.
This version validates checksums when installing gems: https://github.com/bundler/bundler/blob/5553e99a91a07bfd35925b88a5b3c9362f363841/CHANGELOG.md#1140pre1-2016-12-29
```
(More info: The expected SHA256 checksum was
"6779a7cd1495ca3df9ebf42f1081146ddcefe65dd8005c4ad07dd1e8ffd6ba09", but the
checksum for the downloaded gem was
"7b4743f1e5775098a36d4c3f0f6671cde50f9c9dea6c605a1e4f89299dcad33f".)
```
I've downloaded the gem manually and the checksum matched what bundler is
generating, so it seems like rubygems is wrong. I'm not seeing any difference
between the contents of the gem, and what we expect to be released.
Hopefully publishing a new version resolves the problem.
=> Bump version

README.md
RabbitMQ link to the ops manual is outdated. The GOV.UK developer docs
are now the source of truth.
=> Update link from ops manual to developer docs

CHANGELOG.md, lib/govuk_message_queue_consumer/consumer.rb, lib/govuk_message_queue_consumer/json_processor.rb
We've retired Airbrake and are now using Sentry via the govuk_app_config gem, which exposes the GovukError class.
=> Use GovukError for error reporting

README.md
Just link to rubygems where you can copy and paste the right Gemfile line.
=> Don't tell people to install old versions

govuk_message_queue_consumer.gemspec
The version specified is from December 2015. We're using bunny 2.11
in email-alert-service and publishing-api. rummager and
content-performance-manager will be affected by this
upgrade.
https://github.com/ruby-amqp/bunny/blob/master/ChangeLog.md
=> Bump bunny from ~> 2.2.2 to ~> 2.11

lib/govuk_message_queue_consumer/test_helpers/mock_message.rb
This adds public access for payload, delivery_info and headers on mock message instances. This is helpful for tests using the mock message class and have expectations based on these attributes.
=> Add attribute readers to mock message class

spec/batch_consumer_spec.rb
The tests examples for the BatchConsumer rely on the concurrency and timings between threads. Tests for the batch consumer's timeout could intermittently fail. This is due to processor thread potentially not being scheduled for long enough for the timeout to elapse before the subsequent messages are sent. This is not an absolute fix, but should lower the probability of the test failing.
=> Fix intermittently failing batch consumer tests

CHANGELOG.md, lib/govuk_message_queue_consumer/consumer.rb
This adds the ability to overwrite the default subscribe options for the Consumer. This is needed for setting up concurrent consumers as the `block` option needs to be set as false.
=> Add subscribe options for Consumer

CHANGELOG.md, lib/govuk_message_queue_consumer/batch_consumer.rb, lib/govuk_message_queue_consumer/consumer.rb
These are normal, in the sense that Upstart will SIGTERM consumers
when they're being restarted, as part of a deployment for example.
=> Stop reporting SignalExceptions

.github/workflows/ci.yml, Jenkinsfile
As per RFC-123, which specified that we would switch from Jenkins to Github Actions for our gems.
[This PR](https://github.com/alphagov/govuk_message_queue_consumer/pull/73) needs to be merged first, as it removes unused code that is not compatible with ruby 3.0 (it would be possible to make it compatible but since it's unused we've decided to remove instead). After this github actions PR is merged, we can then release the code removal change to test the release process :-)
Also, before this PR is merged someone with access will need to:
* remove branch protection; and
* add the github secret
[Trello](https://trello.com/c/QrxjshEm/270-move-ruby-gems-from-jenkins-to-github-actions)
=> Switch to github actions

CHANGELOG.md, lib/govuk_message_queue_consumer/version.rb
This major version removes the batch consumer, an experimental feature introduced in 2018 that was never used in production.
Do not merge yet, to be merged first:
* [TLC for this repo](https://github.com/alphagov/govuk_message_queue_consumer/pull/74) ✅
* [Switch to github actions](https://github.com/alphagov/govuk_message_queue_consumer/pull/74) - this way we can test the new actions-based release process
=> Release major version 4.0.0

README.md
Removed cache clearing service reference as the application has been retired.
https://trello.com/c/ENPwB2vT/41-retire-cache-clearing-service
https://trello.com/c/TX9wLihh/101-cache-clearing-app-exists-and-we-dont-think-its-necessary-replacing-cache-clearing-app-only-clears-path-not-query-strings
=> Removed cache clearing service reference

CHANGELOG.md, lib/govuk_message_queue_consumer/consumer.rb, spec/govuk_message_queue_consumer/consumer_spec.rb
Our tooling both past (Upstart?) and present (Kubernetes) sends a `SIGTERM` signal to notify a process that it should gracefully shut down. At the moment, this library doesn't properly handle this - it does rescue the error, but does so in the wrong place (so it's not actually handled) and indiscriminately exits with a non-zero exit code.
- Ensure `SignalException`s raised in `Bunny::Queue#subscribe` (rather than the block passed to it) are rescued
- Exit cleanly when receiving a `SignalException` (the comment next to `exit(1)` used to say "ensure rabbitmq requeues outstanding messages", but that has nothing to do with the exit code, it happens by default if the message hasn't been acked by then)
- Only report a signal exception when it's not a vanilla `SIGTERM`
- Add test for signal …
=> Fix broken handling of signals

CHANGELOG.md, lib/govuk_message_queue_consumer/test_helpers/mock_message.rb
`OpenStruct` is used by `MockMessage` to represent a message's headers and delivery information, but the file (or indeed the entire library) does not actually require the `ostruct` library which provides this type.
Many of our projects will somehow transitively require it anyway as it's extensively used in Ruby, so this omission hasn't caused issues so far, but we've encountered a problem on `search-api-v2` now where a completely unrelated dependency was updated and no longer uses `ostruct`, causing tests that use `MockMessage` to fail as the library is no longer loaded.
=> Add explicit require where `OpenStruct` is used

CHANGELOG.md, govuk_message_queue_consumer.gemspec
`ostruct` is deprecated from the standard library, and will no longer be implicitly available from Ruby 3.5.0:
https://bugs.ruby-lang.org/issues/20309
This adds an explicit gem dependency so we can continue using it in the future, and to make the deprecation warnings go away in consumers (pun intended) of this gem.
=> Add explicit dependency on `ostruct` gem
